package rules
import com.java.xdd.drools.bean.Person                    // 导入类
   dialect  "mvel"

   rule "age"                                          // 规则名，唯一
       when
           $person : Person(age<16 || age>50)          //规则的条件部分
       then
       System.out.println($person.getName()+":的年龄为"+$person.getAge()+"====不符合要求！");
   end
   rule "rightAge"                                      // 规则名，唯一
        when
             $person : Person(age>=16 && age<=50)       //规则的条件部分
        then
            System.out.println($person.getName()+":的年龄为"+$person.getAge()+"====符合要求！");
   end